title:            'DKershner.com'
description:      'Full-Stack Developer/Programmer, Data Analyst, Accountant, Strategy - eFormed Partners'

github:
  owner_name: Derek Kershner

linkedIn:         https://www.linkedin.com/in/derek-kershner-54b3392/

theme: jekyll-theme-slate

show-downloads:   false