title:            'DKershner.com'
description:      'Full-Stack Developer/Programmer, Data Analyst, Accountant, Strategy'

github:
  owner_name:     Derek Kershner
  is_project_page: true

header-links:
  linkedIn:         https://www.linkedin.com/in/derek-kershner-54b3392/

theme:            jekyll-theme-slate

paginate: 5

show-downloads:   false