name: Deploy

on: 
  push:
    branches:
      - master



jobs:
  build-and-deploy-aws:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: |
          npm ci
          npm i -g aws-cdk
          npm run build
          cdk synth
          cdk deploy --all --require-approval never
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
