name: Continuous Integration-Deployment to Github Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: NPM
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm i
      - run: npm run lint
      - run: npm test
      - run: npm run build
      - run: npm run export
        env:
          CI: true
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: export
          path: out
  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Download build artifact
        uses: actions/download-artifact@v1
        with:
          name: export
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: export
