name: GitHub - Asana Job CRON 2 # The copies are just because GH Actions sucks at CRON-ing

on:
  schedule:
    - cron: "5,20,35,50 * * * *"

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Call API
      id: githubAsana
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://dkershner.com/api/jobs/github-asana'
        method: 'POST'
        timeout: 60000
    
    - name: Log it out
      run: echo ${{ steps.githubAsana.outputs }}
                  