name: GitHub - Asana Job CRON

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Call API
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://dkershner.com/api/jobs/github-asana'
        method: 'POST'
                  